# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
# ASP.NET
trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:SkipInvalidConfigurations=true /p:PublishProfile=docker /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'



# - task: Docker@2
#   inputs:
#     containerRegistry: 'DockerRegistry'
#     repository: 'ContosoBicycle'
#     command: 'buildAndPush'
#     Dockerfile: 'ContosoBicycle/Dockerfile'
#     buildContext: 'ContosoBicycle'


- task: Docker@2
  inputs:
    displayName: Build and Push API Image
    command: buildAndPush
    containerRegistry: 'DockerRegistry'
    repository: 'Contosoapi'
    tags: $(Build.BuildId)
    command: 'buildAndPush'
    Dockerfile: 'Contoso.APi/Dockerfile'
    buildContext: 'Contoso.APi'

# Deploy to AKS
# - task: KubernetesManifest@0
#   inputs:
#     action: 'deploy'
#     kubernetesServiceConnection: 'aks-k8s-cluster'
#     namespace: 'default'
#     manifests: |
#       kubernetes/api-deployment.yaml
#       kubernetes/api-service.yaml
#       kubernetes/web-deployment.yaml
#       kubernetes/web-service.yaml
#     containers: |
#       workshoprrp.azurecr.io/contosoapi:$(Build.BuildId)
#       workshoprrp.azurecr.io/contosobicycle:$(Build.BuildId)

#deploy to App Service
# - task: AzureWebAppContainer@1
#   inputs:
#     azureSubscription: 'Visual Studio Enterprise(87238ee9-fa25-49fe-a558-72e31e56b9f4)'
#     appName: 'ContosoBicycle'
#     containers: 'workshoprrp.azurecr.io/contosoapi:$(Build.BuildId)'