version: '3.4'

services:
  contosobicycle:
    image: ${DOCKER_REGISTRY-}contosobicycle
    build:
      context: .\ContosoBicycle
      dockerfile: Dockerfile
    environment:
      APPSETTING_APIURL: "http://contoso.api/api/healthcheck"
    depends_on:
      - contoso.api

  contoso.api:
    image: ${DOCKER_REGISTRY-}contosoapi
    build:
      context: .\Contoso.Api
      dockerfile: Dockerfile
    environment:
      CONNSTR_AnimalContext: "Server=contoso-sql;Initial Catalog=ContosoBicycle;User ID=sa;Password=P@ssword123!"
    depends_on:
        - contoso-sql

  contoso-sql:
    image:  microsoft/mssql-server-windows-express
    environment:
      sa_password: "P@ssword123!"
      ACCEPT_EULA: "Y"

