on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: workshoprrp.azurecr.io
        username: ${{ secrets.acr_workshoprrp_username }}
        password: ${{ secrets.acr_workshoprrp_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/ContosoBicycle" -f  "ContosoBicycle/Dockerfile" -t workshoprrp.azurecr.io/aksk8scluster:${{ github.sha }} --label dockerfile-path=ContosoBicycle/Dockerfile
        docker push workshoprrp.azurecr.io/aksk8scluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_aksk8scluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep development | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace development`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: development
        container-registry-url: workshoprrp.azurecr.io
        container-registry-username: ${{ secrets.acr_workshoprrp_username }}
        container-registry-password: ${{ secrets.acr_workshoprrp_password }}
        secret-name: aksk8sclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: development
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          workshoprrp.azurecr.io/aksk8scluster:${{ github.sha }}
        imagepullsecrets: |
          aksk8sclustedockerauth
